[2022-08-15T15:52:28.301] [FATAL] default - A ocurrido un error al iniciar la base MongoServerError: bad auth : Authentication failed.
    at Connection.onMessage (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:210:30)
    at MessageStream.<anonymous> (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:63:60)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:132:20)
    at MessageStream._write (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
[2022-08-15T15:53:43.462] [FATAL] default - A ocurrido un error al iniciar la base: 
	 MongoServerError: bad auth : Authentication failed.
    at Connection.onMessage (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:210:30)
    at MessageStream.<anonymous> (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:63:60)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:132:20)
    at MessageStream._write (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:390:28)
[2022-08-15T21:32:19.374] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: MongoID is not defined
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:186:72)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:52:45)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:50:36
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:354:9)
    at Authenticator.deserializeUser (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:359:5)
    at SessionStrategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\strategies\session.js:61:10)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\index.js:328:13) 
[2022-08-15T21:34:50.504] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: MongoID is not defined
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:186:72)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:52:45)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:50:36
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:354:9)
    at Authenticator.deserializeUser (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:359:5)
    at SessionStrategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\strategies\session.js:61:10)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\index.js:328:13) 
[2022-08-15T22:14:37.567] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Unable to find the session to touch
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\connect-mongo\build\main\lib\MongoStore.js:326:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-15T22:20:33.532] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Unable to find the session to touch
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\connect-mongo\build\main\lib\MongoStore.js:326:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-15T22:47:21.232] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: error is not defined
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Routers/routerSessions.js:9:5
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at complete (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:271:13)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:278:15
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:428:14)
    at Authenticator.transformAuthInfo (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:450:5)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:275:22
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\http\request.js:41:7
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\sessionmanager.js:51:9 
[2022-08-15T22:48:12.987] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: next is not defined
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Routers/routerSessions.js:10:9
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at complete (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:271:13)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:278:15
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:428:14)
    at Authenticator.transformAuthInfo (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:450:5)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:275:22
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\http\request.js:41:7
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\sessionmanager.js:51:9 
[2022-08-15T23:15:21.217] [FATAL] default - ReferenceError: datos is not defined
    at ValidUser (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:63:5)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:12:16)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
[2022-08-15T23:15:21.223] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: datos is not defined
    at ValidUser (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:63:5)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:12:16)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) 
[2022-08-15T23:16:22.435] [ERROR] default - Error: Se requieren mas datos para completar esta accion
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:13:27)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) {
  tipo: 'MISSING_DATA'
}
[2022-08-15T23:20:24.675] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 SyntaxError: Unexpected string in JSON at position 97
    at JSON.parse (<anonymous>)
    at parse (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at invokeCallback (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:231:16)
    at done (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[2022-08-15T23:20:42.679] [ERROR] default - Error: Se requieren mas datos para completar esta accion
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:13:27)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) {
  tipo: 'MISSING_DATA'
}
[2022-08-15T23:21:23.390] [ERROR] default - Error: Se requieren mas datos para completar esta accion
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:13:27)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) {
  tipo: 'MISSING_DATA'
}
[2022-08-15T23:24:07.631] [ERROR] default - Error: Se requieren mas datos para completar esta accion
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:13:27)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) {
  tipo: 'MISSING_DATA'
}
[2022-08-15T23:25:00.280] [ERROR] default - Error: Se requieren mas datos para completar esta accion
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:13:27)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) {
  tipo: 'MISSING_DATA'
}
[2022-08-15T23:26:09.549] [ERROR] default - Error: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:191:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:51:33)
    at async file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:54:22 {
  tipo: 'NOT_FOUND'
}
[2022-08-15T23:26:09.554] [ERROR] default - NOT_FOUND: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
[2022-08-15T23:26:45.549] [ERROR] default - Error: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:191:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:51:33)
    at async file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:54:22 {
  tipo: 'NOT_FOUND'
}
[2022-08-15T23:26:45.551] [ERROR] default - NOT_FOUND: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
[2022-08-15T23:29:36.627] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 SyntaxError: Unexpected token } in JSON at position 215
    at JSON.parse (<anonymous>)
    at parse (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at invokeCallback (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:231:16)
    at done (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[2022-08-15T23:29:44.138] [ERROR] default - Error: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:191:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:51:33)
    at async file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:54:22 {
  tipo: 'NOT_FOUND'
}
[2022-08-15T23:29:44.140] [ERROR] default - NOT_FOUND: El elemento con id 62fb000ec11fa58d8cfab83f no fue encotrado
[2022-08-16T16:42:15.190] [ERROR] default - Error: Usuario ya regitrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:52:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:17:29)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:26) {
  tipo: 'DUPLICATED_USER'
}
[2022-08-16T17:41:55.650] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Unable to find the session to touch
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\connect-mongo\build\main\lib\MongoStore.js:326:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-16T18:03:57.132] [FATAL] default - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) {
  input: './api/carrito',
  code: 'ERR_INVALID_URL'
}
[2022-08-16T18:03:57.141] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) 
[2022-08-16T18:05:17.150] [FATAL] default - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) {
  input: '/api/carrito',
  code: 'ERR_INVALID_URL'
}
[2022-08-16T18:05:17.156] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) 
[2022-08-16T18:07:10.040] [FATAL] default - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) {
  input: '/api/carrito/',
  code: 'ERR_INVALID_URL'
}
[2022-08-16T18:07:10.047] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) 
[2022-08-16T18:07:47.569] [FATAL] default - TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) {
  input: './api/carrito/',
  code: 'ERR_INVALID_URL'
}
[2022-08-16T18:07:47.578] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/request.js:55:16)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:51:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12) 
[2022-08-16T18:14:51.768] [FATAL] default - TypeError: node-fetch cannot load localhost:8080/api/carrito/. URL scheme "localhost" is not supported.
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:54:10
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
[2022-08-16T18:14:51.774] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: node-fetch cannot load localhost:8080/api/carrito/. URL scheme "localhost" is not supported.
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:54:10
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13) 
[2022-08-16T19:15:30.143] [FATAL] default - TypeError: node-fetch cannot load localhost:8080/api/carrito/. URL scheme "localhost" is not supported.
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:54:10
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
[2022-08-16T19:15:30.149] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: node-fetch cannot load localhost:8080/api/carrito/. URL scheme "localhost" is not supported.
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:54:10
    at new Promise (<anonymous>)
    at fetch (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/node_modules/node-fetch/src/index.js:49:9)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:18:36)
    at Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:40)
    at Strategy.authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport-local\lib\strategy.js:88:12)
    at attempt (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:369:16)
    at authenticate (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:370:7)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13) 
[2022-08-16T19:18:14.789] [ERROR] default - Error: El elemento con id 62fc1718124a9a90031cd594 no fue encotrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:192:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:53:33)
    at async file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:54:22 {
  tipo: 'NOT_FOUND'
}
[2022-08-16T19:18:14.795] [ERROR] default - NOT_FOUND: El elemento con id 62fc1718124a9a90031cd594 no fue encotrado
[2022-08-16T19:38:16.207] [ERROR] default - Error: El elemento con id 62fc1bb974ef028d80dd8eff no fue encotrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:192:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.getByID (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:53:33)
    at async file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:54:22 {
  tipo: 'NOT_FOUND'
}
[2022-08-16T19:38:16.213] [ERROR] default - NOT_FOUND: El elemento con id 62fc1bb974ef028d80dd8eff no fue encotrado
[2022-08-16T19:39:51.442] [ERROR] default - Error: Usuario ya regitrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:53:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:20:29)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:26) {
  tipo: 'DUPLICATED_USER'
}
[2022-08-16T19:40:33.041] [ERROR] default - Error: Usuario ya regitrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:53:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:20:29)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:26) {
  tipo: 'DUPLICATED_USER'
}
[2022-08-16T19:41:09.527] [ERROR] default - Error: Usuario ya regitrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:53:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:20:29)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:17:26) {
  tipo: 'DUPLICATED_USER'
}
[2022-08-16T21:11:19.952] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Unable to find the session to touch
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\connect-mongo\build\main\lib\MongoStore.js:326:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-16T21:12:20.068] [ERROR] default - Error: Error de Autenticacion, credenciales no validas
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.autenticar (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:38:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:36:26) {
  tipo: 'AUTHE_ERROR'
}
[2022-08-17T11:15:55.315] [ERROR] default - Error: Usuario ya regitrado
    at crearError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:32:19)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Class/Class_Mongo.js:53:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:19:29)
    at async Strategy._verify (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/passport.js:19:26) {
  tipo: 'DUPLICATED_USER'
}
[2022-08-17T12:33:59.027] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Unable to find the session to touch
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\connect-mongo\build\main\lib\MongoStore.js:326:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-17T12:34:41.131] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: id is not defined
    at UsuarioDaoMongoDb.ChangeUserlROL (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Usuarios/UsuarioDaoMongoDb.js:61:13)
    at ChangeUserRol (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/UserController.js:25:27)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at AdminCheck (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/UserSesion.js:23:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-17T12:48:47.978] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: user is not defined
    at success (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Routers/routerSessions.js:18:17)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at complete (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:271:13)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:278:15
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:428:14)
    at Authenticator.transformAuthInfo (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:450:5)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:275:22
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\http\request.js:41:7
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\sessionmanager.js:51:9 
[2022-08-17T12:56:05.289] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: Cannot read properties of undefined (reading 'EMAIL')
    at successLogin (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Routers/routerSessions.js:18:73)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at complete (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:271:13)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:278:15
    at pass (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:428:14)
    at Authenticator.transformAuthInfo (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\authenticator.js:450:5)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\middleware\authenticate.js:275:22
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\http\request.js:41:7
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\passport\lib\sessionmanager.js:51:9 
[2022-08-17T17:34:56.045] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: ObjectId is not defined
    at ProductosDaoMongoDb.changeStock (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/DAOs/Productos/ProductosDaoMongoDb.js:22:29)
    at Object.DecreseStock (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:99:56)
    at BuyChopCart (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorCarrito.js:76:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-08-17T17:36:54.877] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: Permission to send an SMS has not been enabled for the region indicated by the 'To' number: 3512647826.
    at success (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\twilio\lib\base\Version.js:135:15)
    at Promise_then_fulfilled (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\q\q.js:766:44)
    at Promise_done_fulfilled (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\q\q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\q\q.js:1229:9)
    at Pending_become_eachMessage_task (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\q\q.js:1369:30)
    at RawTask.call (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\asap\asap.js:40:19)
    at flush (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\asap\raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
[2022-08-17T20:42:31.557] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 SyntaxError: Unexpected token } in JSON at position 188
    at JSON.parse (<anonymous>)
    at parse (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at invokeCallback (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:231:16)
    at done (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[2022-08-17T21:20:23.834] [ERROR] default - NOT_FOUND: El producto con id 62fd84828bd6bab6a011730c no se encuntra en el carrito
[2022-08-17T21:24:12.278] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 SyntaxError: Unexpected token + in JSON at position 176
    at JSON.parse (<anonymous>)
    at parse (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\types\json.js:89:19)
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at invokeCallback (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:231:16)
    at done (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
[2022-08-17T21:29:41.693] [ERROR] default - MISSING_DATA: El id debe contener 24 caracteres
[2022-08-17T21:30:25.907] [ERROR] default - NOT_FOUND: El elemento con id 62fd84828bd6bab6a011780c no fue encotrado
[2022-10-05T12:47:49.796] [ERROR] default - MISSING_DATA: "Contraseña" es un campo requerido
[2022-10-05T12:53:11.492] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: Cannot add property _id, object is not extensible
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:65:21
    at Array.map (<anonymous>)
    at prepareDocs (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:63:17)
    at new InsertOneOperation (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\insert.js:42:74)
    at Collection.insertOne (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\collection.js:149:78)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DB/Class_Mongo.js:11:41)
    at UsuarioDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DAOs/Usuarios/UsuarioDaoMongoDb.js:11:25)
    at UsuariosAPI.createNewUser (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Usuarios.js:21:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async register (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/UserController.js:21:29) 
[2022-10-05T12:58:17.746] [ERROR] default - MISSING_DATA: "id" es un campo requerido
[2022-10-05T13:04:03.817] [ERROR] default - MISSING_DATA: "id" es un campo requerido
[2022-10-05T13:04:38.520] [ERROR] default - MISSING_DATA: "id" es un campo requerido
[2022-10-05T13:06:36.497] [ERROR] default - DUPLICATED_USER: Usuario ya regitrado
[2022-10-05T13:06:44.315] [ERROR] default - MISSING_DATA: "id" es un campo requerido para crear el carrito
[2022-10-05T13:07:45.588] [ERROR] default - DUPLICATED_USER: Usuario ya regitrado
[2022-10-05T13:07:56.275] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 MongoServerError: Write batch sizes must be between 1 and 100000. Got 0 operations.
    at Connection.onMessage (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:210:30)
    at MessageStream.<anonymous> (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\connection.js:63:60)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:132:20)
    at MessageStream._write (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:390:28) 
[2022-10-05T13:11:49.337] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: Cannot add property _id, object is not extensible
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:65:21
    at Array.map (<anonymous>)
    at prepareDocs (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:63:17)
    at new InsertOneOperation (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\insert.js:42:74)
    at Collection.insertOne (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\collection.js:149:78)
    at CarritoDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DB/Class_Mongo.js:12:41)
    at CarritoDaoMongoDb.create (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DAOs/Carrito/CarritoDaoMongoDb.js:10:27)
    at CarritoAPI.CreateNew (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Carrito.js:27:33)
    at UsuariosAPI.createNewUser (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Usuarios.js:22:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[2022-10-05T13:15:10.332] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: CarritoDao.getByID is not a function
    at CarritoAPI.DisplayProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Carrito.js:47:46)
    at DisplayProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorCarrito.js:30:54)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\route.js:144:13)
    at file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/UserSesion.js:25:7
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\jsonwebtoken\verify.js:223:12
    at getSecret (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\jsonwebtoken\verify.js:90:14)
    at Object.module.exports [as verify] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\jsonwebtoken\verify.js:94:10)
    at UserHasSesion (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Middleware/UserSesion.js:16:9)
    at Layer.handle [as handle_request] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\express\lib\router\layer.js:95:5) 
[2022-10-05T14:29:32.388] [ERROR] default - MISSING_DATA: "Nombre"es un campo requerido
[2022-10-05T14:30:55.648] [ERROR] default - MISSING_DATA: "Nombre"es un campo requerido
[2022-10-05T14:37:21.762] [ERROR] default - MISSING_DATA: "NAME" es un campo requerido
[2022-10-05T14:39:20.842] [ERROR] default - MISSING_DATA: "id" es un campo requerido
[2022-10-05T14:39:40.112] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 Error: El nombre debe contener menos de 50 caracteres
    at createError (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:85:19)
    at Object.WRONG_DATA (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Tools/Error_Generator.js:72:16)
    at Product.set name [as name] (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/Class/Product.js:26:51)
    at new Product (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/Class/Product.js:12:17)
    at ProductosApi.CreateNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Productos.js:19:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AddNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:25:34) 
[2022-10-05T15:01:17.502] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: description is not defined
    at new Product (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/Class/Product.js:13:26)
    at ProductosApi.CreateNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Productos.js:19:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AddNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:25:34) 
[2022-10-05T15:08:32.383] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: Cannot add property _id, object is not extensible
    at D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:65:21
    at Array.map (<anonymous>)
    at prepareDocs (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\common_functions.js:63:17)
    at new InsertOneOperation (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\operations\insert.js:42:74)
    at Collection.insertOne (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\mongodb\lib\collection.js:149:78)
    at ProductosDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DB/Class_Mongo.js:12:41)
    at ProductosDaoMongoDb.save (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DAOs/Productos/ProductosDaoMongoDb.js:11:25)
    at ProductosApi.CreateNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Productos.js:20:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AddNewProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:25:34) 
[2022-10-05T15:13:24.806] [ERROR] default - MISSING_DATA: "NAME" es un campo requerido
[2022-10-05T15:13:43.541] [ERROR] default - NOT_FOUND: Recurso no encontrado
[2022-10-05T15:29:38.952] [ERROR] default - MISSING_DATA: "id" es un campo requerido para crear el carrito
[2022-10-05T15:38:47.064] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: product is not defined
    at ShopCart.addProduct (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/Class/Carrito.js:33:18)
    at CarritoAPI.AddProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Carrito.js:37:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AddProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorCarrito.js:20:13) 
[2022-10-05T15:41:32.227] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: datosDeUsuario is not defined
    at ProductosApi.UpdateProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Productos.js:59:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UpdateProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:37:33) 
[2022-10-05T15:52:26.476] [ERROR] default - MISSING_DATA: "id" es un campo requerido
[2022-10-05T15:54:37.528] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 ReferenceError: productoBuscado is not defined
    at ProductosDaoMongoDb.getById (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Models/DAOs/Productos/ProductosDaoMongoDb.js:32:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ProductosApi.UpdateProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Productos.js:57:37)
    at async UpdateProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorProductos.js:37:33) 
[2022-10-05T17:10:20.180] [ERROR] default - NOT_FOUND: Recurso no encontrado
[2022-10-05T17:14:37.374] [ERROR] default - NOT_FOUND: Recurso no encontrado
[2022-10-05T17:17:08.139] [ERROR] default - NOT_FOUND: Recurso no encontrado
[2022-10-05T17:19:01.827] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 TypeError: carrito.PRODUCTS is not iterable
    at CarritoAPI.DisplayProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/APIs/API_Carrito.js:49:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DisplayProd (file:///D:/Ale/Documentos/Curso_BackEnd/Proyecto_Final/Controllers/ControladorCarrito.js:30:36) 
[2022-10-05T17:23:13.546] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:24:25.405] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:25:39.727] [ERROR] default - MISSING_DATA: "Email" es un campo requerido
[2022-10-05T17:27:40.344] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:29:52.764] [ERROR] default - AUTHE_ERROR: Error de Autenticacion, credenciales no validas
[2022-10-05T17:30:25.911] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:31:50.641] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:34:02.797] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:35:46.832] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:36:52.398] [ERROR] default - DUPLICATED_PRODUCT: Producto Dupliacado
[2022-10-05T17:43:35.062] [ERROR] default - MISSING_DATA: "id" es un campo requerido para crear el carrito
[2022-10-05T21:42:20.577] [ERROR] default - NOT_FOUND: Recurso no encontrado
[2022-10-06T13:47:06.863] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 MulterError: Unexpected field
    at wrappedFileFilter (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\multer\index.js:40:19)
    at Multipart.<anonymous> (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\multer\lib\make-middleware.js:107:7)
    at Multipart.emit (node:events:390:28)
    at HeaderParser.cb (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:358:14)
    at HeaderParser.push (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:162:20)
    at SBMH.ssCb [as _cb] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:394:37)
    at feed (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:389:12) 
[2022-10-06T13:47:57.881] [FATAL] default - ATENCION: A ocurrido un error sin manejo especifico. 
	 MulterError: Unexpected field
    at wrappedFileFilter (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\multer\index.js:40:19)
    at Multipart.<anonymous> (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\multer\lib\make-middleware.js:107:7)
    at Multipart.emit (node:events:390:28)
    at HeaderParser.cb (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:358:14)
    at HeaderParser.push (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:162:20)
    at SBMH.ssCb [as _cb] (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:394:37)
    at feed (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\streamsearch\lib\sbmh.js:219:14)
    at SBMH.push (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\streamsearch\lib\sbmh.js:104:16)
    at Multipart._write (D:\Ale\Documentos\Curso_BackEnd\Proyecto_Final\node_modules\busboy\lib\types\multipart.js:567:19)
    at writeOrBuffer (node:internal/streams/writable:389:12) 
